name: {{project_name}}
description: A new Flutter project created with Mason.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Navigation
  go_router: ^12.0.0
  
  # DI
  get_it: ^7.6.0
  
  # Networking
  dio: ^5.8.0
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  dio_http_formatter: ^3.3.0
  
  # Utils
  freezed_annotation: ^2.4.4
  equatable: ^2.0.7
  either_dart: ^1.0.0
  shared_preferences: ^2.5.3
  app_links: ^3.4.5
  app_badge_plus: ^1.1.0
  connectivity_plus: ^6.0.0
  device_info_plus: ^11.1.0
  share_plus: ^10.1.1
  flutter_svg: ^2.0.17
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  logger: ^2.5.0
  in_app_review: ^2.0.10
  uuid: ^4.4.0
  
  # Localization
  slang: ^3.28.0
  slang_flutter: ^3.28.0
  
  # Firebase & Supabase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_analytics: ^11.4.0
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.3.4
  firebase_remote_config: ^5.2.2
  cloud_firestore: ^5.6.0
  supabase_flutter: ^2.3.2
  
  # Storage
  flutter_secure_storage: ^9.2.4
  mime: ^2.0.0
  flutter_cache_manager: ^3.3.1
  
  # IO & Platform
  universal_io: ^2.2.2
  file: ^7.0.0
  path: ^1.9.0
  universal_html: ^2.2.4
  
  # Analytics
  amplitude_flutter: ^4.3.1
  appsflyer_sdk: ^6.14.3
  
  # Additional Utils
  dartx: ^1.2.0
  android_id: ^0.4.0
  crypto: ^3.0.3
  
  # Permissions & Tracking
  permission_handler: ^11.3.0
  app_tracking_transparency: ^2.0.4
  
  # Firebase Crashlytics
  firebase_crashlytics: ^4.0.0
  
  # Logging
  palestine_console: ^2.0.0
  
  # Smartlook Analytics
  flutter_smartlook: ^4.1.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.5
  
  # Code Generation
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  slang_build_runner: ^3.28.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/svg/
    - assets/png/
