name: {{project_name}}
description: A new Flutter project created with Mason.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Navigation
  go_router: ^12.0.0
  
  # DI
  get_it: ^7.6.0
  injectable: ^2.3.2
  
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Utils
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
